---

- name: start docker
  systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: stop docker
  systemd:
    name: docker
    state: stopped
  become: true

- name: restart docker
  become: true
  systemd:
    name: docker
    state: restarted
    enabled: true
    daemon_reload: true

# Handler showing how to clean yum metadata cache
- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: false
