---
# Standards: 0.2
- hosts: all
  become: true
  pre_tasks:
    - name: remove docker
      yum:
        state: absent
        name:
          - docker-latest
          - docker

  roles:
    - role: base_epel
    - role: base_docker
