---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: instance
    box: redesign/centos7
    box_url: https://app.vagrantup.com/redesign/boxes/centos7

provisioner:
  name: ansible
verifier:
  name: ansible
